server:
  port: 8080

spring:
  profiles:
    active: local    # 启动时加载 local 配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

upload:
  path: uploads

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: "change-me-in-local-config-at-least-32-chars!!"
  expire: 86400000